/**
 * Datos de ejemplo para capturas (sin API). Misma imagen en todos (Plaza de Majagual).
 */
var IMAGEN_MAJAGUAL = "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1200&auto=format&fit=crop";
window.SITIOS_EJEMPLO = [
  {
    id: "1",
    nombre: "Parque Santander",
    tipo: "Parque",
    direccion: "Calle 18 con Carrera 21, barrio Centro, Sincelejo, Sucre",
    valorEntrada: 0,
    horario: "24 horas",
    descripcion: "Corazón verde del centro de Sincelejo. Ideal para caminar, sentarse a leer o compartir con la familia. Punto de encuentro de eventos culturales y ferias. Los fines de semana hay actividades para niños y venta de artesanías.",
    puntoReferencia: "Frente a la Catedral de San Francisco de Asís",
    fechaSubida: "12 de enero de 2026",
    servicios: ["Baños públicos", "Zonas verdes", "Sillas y bancas"],
    foto1: IMAGEN_MAJAGUAL,
    foto2: IMAGEN_MAJAGUAL,
    foto3: IMAGEN_MAJAGUAL,
    foto4: IMAGEN_MAJAGUAL,
    video1: "https://www.youtube.com/watch?v=fN0R-Fw-Ads",
    lat: 9.3047,
    lng: -75.3959
  },
  {
    id: "2",
    nombre: "Estadio 20 de Enero",
    tipo: "Estadio",
    direccion: "Carrera 14 con Calle 20, Sincelejo, Sucre",
    valorEntrada: 15000,
    horario: "Según programación de partidos y eventos",
    descripcion: "Sede de fútbol y eventos deportivos. Aquí se vive la pasión del fútbol sincelejano y se realizan conciertos y actividades masivas. Instalaciones con graderías cubiertas y buen acceso.",
    puntoReferencia: "Cerca del Coliseo de Ferias",
    fechaSubida: "18 de enero de 2026",
    servicios: ["Graderías cubiertas", "Parqueadero", "Baños"],
    foto1: IMAGEN_MAJAGUAL,
    foto2: IMAGEN_MAJAGUAL,
    foto3: IMAGEN_MAJAGUAL,
    foto4: IMAGEN_MAJAGUAL,
    video1: "https://www.youtube.com/watch?v=fN0R-Fw-Ads",
    lat: 9.2985,
    lng: -75.4012
  },
  {
    id: "3",
    nombre: "Plaza de Majagual",
    tipo: "Restaurante",
    direccion: "Carrera 19 # 20-15, Sincelejo, Sucre",
    valorEntrada: 0,
    horario: "Lun–Dom 11:00 – 23:00",
    descripcion: "Gastronomía típica sucrense en un ambiente familiar. Recomendado: mote de queso, sancocho y pescado frito. Terraza exterior y atención amable. Ideal para conocer los sabores de la región.",
    puntoReferencia: "A dos cuadras del Parque Santander",
    fechaSubida: "22 de enero de 2026",
    servicios: ["Wi‑Fi", "Terraza exterior", "Parqueadero cercano"],
    foto1: IMAGEN_MAJAGUAL,
    foto2: IMAGEN_MAJAGUAL,
    foto3: IMAGEN_MAJAGUAL,
    foto4: IMAGEN_MAJAGUAL,
    video1: "https://www.youtube.com/watch?v=fN0R-Fw-Ads",
    lat: 9.3021,
    lng: -75.3933
  },
  {
    id: "4",
    nombre: "Centro Recreacional El Cacique",
    tipo: "Centro Recreacional",
    direccion: "Vía Sincelejo–Montería km 2, Sincelejo, Sucre",
    valorEntrada: 8000,
    horario: "Mar–Dom 8:00 – 18:00",
    descripcion: "Piscinas, zonas verdes y áreas para asados. Ideal para plan familiar o con amigos los fines de semana. Cuenta con parqueadero, vestuarios y kioscos para comer.",
    puntoReferencia: "Salida norte de Sincelejo",
    fechaSubida: "5 de febrero de 2026",
    servicios: ["Piscinas", "Asaderos", "Parqueadero"],
    foto1: IMAGEN_MAJAGUAL,
    foto2: IMAGEN_MAJAGUAL,
    foto3: IMAGEN_MAJAGUAL,
    foto4: IMAGEN_MAJAGUAL,
    video1: "https://www.youtube.com/watch?v=fN0R-Fw-Ads",
    lat: 9.3189,
    lng: -75.4102
  },
  {
    id: "5",
    nombre: "Discoteca La 21",
    tipo: "Discoteca",
    direccion: "Carrera 21 # 18-50, Sincelejo, Sucre",
    valorEntrada: 25000,
    horario: "Vie–Dom 22:00 – 4:00",
    descripcion: "Música en vivo y DJ. Ambiente para bailar y vivir la noche sincelejana. Incluye una consumición. Pista amplia y buena iluminación. Recomendado reservar mesa los sábados.",
    puntoReferencia: "Zona rosa, cerca del parque",
    fechaSubida: "1 de marzo de 2026",
    servicios: ["Música en vivo", "Zona VIP", "Parqueadero"],
    foto1: IMAGEN_MAJAGUAL,
    foto2: IMAGEN_MAJAGUAL,
    foto3: IMAGEN_MAJAGUAL,
    foto4: IMAGEN_MAJAGUAL,
    video1: "https://www.youtube.com/watch?v=fN0R-Fw-Ads",
    lat: 9.3033,
    lng: -75.3921
  },
  {
    id: "6",
    nombre: "Plazoleta de la Catedral",
    tipo: "Plaza",
    direccion: "Calle 18 entre Carreras 20 y 21, Sincelejo, Sucre",
    valorEntrada: 0,
    horario: "24 horas",
    descripcion: "Espacio público frente a la Catedral. Punto de referencia para encuentros y fotos. Ferias artesanales los fines de semana. Lugar emblemático del centro de la ciudad.",
    puntoReferencia: "Frente a la Catedral de San Francisco de Asís",
    fechaSubida: "10 de marzo de 2026",
    servicios: ["Bancos para sentarse", "Zona peatonal", "Ferias artesanales"],
    foto1: IMAGEN_MAJAGUAL,
    foto2: IMAGEN_MAJAGUAL,
    foto3: IMAGEN_MAJAGUAL,
    foto4: IMAGEN_MAJAGUAL,
    video1: "https://www.youtube.com/watch?v=fN0R-Fw-Ads",
    lat: 9.3051,
    lng: -75.3948
  }
];
