BEGIN;

CREATE TABLE IF NOT EXISTS public.sitios (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(200) NOT NULL,
  categoria varchar(100) NOT NULL,
  descripcion_corta text,
  descripcion text,
  direccion varchar(300),
  valor_entrada varchar(100),
  horario varchar(200),
  punto_referencia varchar(200),
  lat double precision,
  lng double precision,
  imagen_portada varchar(500),
  imagen_1 varchar(500),
  imagen_2 varchar(500),
  imagen_3 varchar(500),
  imagen_4 varchar(500),
  video_url varchar(500),
  destacado boolean DEFAULT false,
  orden integer DEFAULT 0,
  created_at timestamp without time zone,
  updated_at timestamp without time zone
);

CREATE INDEX IF NOT EXISTS idx_sitios_categoria ON public.sitios (categoria);
CREATE INDEX IF NOT EXISTS idx_sitios_destacado ON public.sitios (destacado);
CREATE INDEX IF NOT EXISTS idx_sitios_orden ON public.sitios (orden DESC);

COMMIT;
